### ISSUE TITLE
Remove Mansion: FFA

### ISSUE THREAD

**Issue by SheriffSoco** [OvercastNetwork/Rotations#365] opened 2015-01-17 19:50 UTC
It's a laggy as heck map and doesn't deserve to be played.

Along with this. Please make the GS Rotations unique. It's the same two rotations with different order maps

**Comment by ItsMiiOlly** [comment] 2015-01-17 20:25
Will be working on this.

**Comment by firstvirus92** [comment] 2015-01-17 20:57
FYI duplicate of #331

**Closed** 2015-01-17 21:37 UTC
